from . import views
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import update_terms_and_conditions,admin_referral_list, userProfileData, updateUserProfile, profilePictureUpload, create_terms_and_conditions

urlpatterns= [
    path("signup/", views.signup, name='signup'),
    path("verify/", views.verify, name='verify'),
    path("login/", views.login, name='login'),
    path("token/refresh/", TokenRefreshView.as_view(), name='token_refresh'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path("loginVerify/", views.loginverify, name='loginVerify'),
    path("changePassword/", views.changePassword, name='changePassword'),
    path("forgotPassword/", views.forgotPassword, name='forgotPassword'),
    path("forgotPasswordVerify/", views.forgotPasswordVerify,
         name='forgotPasswordVerify'),
    path('setNewPassword/', views.setNewPassword, name='set_new_password'),
    path('api/admin/referrals/', views.admin_referral_list, name='admin-referral-list'),
    path('userProfileData/', views.userProfileData, name='user-Profile-Data'),
    path('updateUserProfile/', views.updateUserProfile, name='update-user-profile'),
    path('profilePictureUpload/', views.profilePictureUpload, name='profile-picture-upload'),
    path('api/terms-and-conditions/', views.create_terms_and_conditions, name='create_terms'),
    path('api/terms-and-conditions/<int:pk>/', views.update_terms_and_conditions, name='update_terms_and_conditions'),
    path('api/terms-and-conditions/delete/<int:pk>/', views.delete_terms_and_conditions, name='delete_terms_and_conditions'),
    path('api/terms-and-conditions/delete/', views.delete_terms_and_conditions),
    path('api/terms-and-conditions/toggle-status/<int:pk>/',views.toggle_terms_status,
    name='toggle_terms_status'),
    path('api/terms-and-conditions/toggle-status/',views.toggle_terms_status,
    name='toggle_terms_status'),
    path('api/terms-and-conditions/list/', views.list_terms_and_conditions, name='list_terms_and_conditions'),
    path('api/terms-and-conditions/active/', views.get_active_terms_and_conditions, name='get_active_terms'),
    path('api/follow_user/<user_id>/', views.follow_user, name='user_api_follow_user'),
    path('api/follow_user/', views.unfollow_user, name='user_api_unfollow_user'),
    path('api/unfollow_user/<user_id>/', views.unfollow_user, name='user_api_unfollow_user'),
    path('api/unfollow_user/', views.unfollow_user, name='user_api_unfollow_user'),
    path('api/follower/', views.list_my_follower, name='follower_list'),
    path('api/following/', views.list_my_following, name='following_list'),
    path('api/admin/follows/', views.admin_list_follows, name='admin_list_follows'),
    path('api/admin/follows/delete/<user_id>/', views.delete_follow, name='delete_follow'),
    path('api/admin/follows/delete/', views.delete_follow, name='delete_follow'),
    path('api/admin/user_follow_data/<user_id>/', views.admin_user_follow_data, name='admin_user_follow_data'),
    path('api/admin/user_follow_data/', views.admin_user_follow_data, name='admin_user_follow_data'),
    path('api/faqs/create/', views.create_faq, name='faq_create'),
    path('api/faqs/', views.list_faq, name='faq_list'),
    path('api/faqs/<str:id>/', views.single_faq, name='returns_single_faq'),
    path('api/faqs/<int:id>/update/', views.update_faq, name='update_faq'),
    path('api/faqs/<int:id>/delete/', views.delete_faq, name='delete_faq'),
]
