# Generated by Django 5.2 on 2025-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_alter_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='new_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
