# Generated by Django 5.2 on 2025-05-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_useraccount_new_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
