# Generated by Django 5.2 on 2025-05-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_remove_useraccount_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
