# Generated by Django 5.2 on 2025-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0009_useraccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
