# Generated by Django 5.2 on 2025-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0013_alter_useraccount_username_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
