# Generated by Django 5.2 on 2025-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0014_useraccount_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
