# Generated by Django 5.2 on 2025-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0015_useraccount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
