# Generated by Django 5.2 on 2025-05-14 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0016_useraccount_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
