# Generated by Django 5.2 on 2025-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0017_useraccount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicture'),
        ),
    ]
