# Generated by Django 5.2.1 on 2025-05-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0023_contactus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('about_us', 'About Us')], max_length=20, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
